### ISSUE TITLE
Keyboard layout is not honored for typing the encryption password/passphrase

### ISSUE THREAD

**Issue by mlncn** [pop-os/gnome-initial-setup#27] opened 2018-06-26 11:55 UTC
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Unknown / just gnome-initial-setup

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

1. Set the keyboard layout to Dvorak or something else that changes character locations.
2. Enable encryption and set the passphrase (it will use the keyboard layout you chose).
3. Restart.
4. Attempt to type the encryption passphrase (it will *not* use the keyboard layout you chose).

**Expected behavior:**

The encryption password/passphrase can be entered in the keyboard layout used in initial setup and/or that was set later; or at a minimum that it is clearly communicated which keyboard layout will be used when the encryption password must be typed to unlock the computer.

**Other Notes:**

My new Oryx Pro out-of-the-box experience, as captured in a support request:

> So just opened the brand new computer, following the prompts.
> 
> I set the keyboard language to English (Dvorak, alt. intl.)
> 
> Not more than a couple screens later, it asks for the encryption password. (That was a little frustrating because there was no password preview option, not even one letter at a time, so i couldn't be certain it was using Dvorak, and i couldn't try out if special characters (option ,c for the ç in my own name for instance) would work.)
> 
> But the really bad bug came when it restarted. Type my passphrase. Doesn't work. Type it again. And again. And again. Locked out. Try typing it with the standard qwerty layout. That was it.
> 
> Bad first experience; if the keyboard layout won't be used on reboot, probably better not to have us set it, or make it clear it won't be operational on first boot.
> 
> The fear i have is that the keyboard layout setting will never apply when typing the encryption password which would be a major annoyance. Will see soon and update!

And:

> And now after a reboot i can confirm that the decryption password does *not* use the chosen keyboard layout when entering it. This is very sad. Is it a bug that can be fixed?
> 
> (The keyboard layout kicks in by the time of the user login.)

**Comment by mmstick** [comment] 2018-06-26 14:30
Something must have changed at some point. This was working before. I'll look into it. In the meantime, I don't think this is the right repo for this issue.

The keyboard layout is set in the installation process via [distinst](https://github.com/pop-os/distinst) & [installer](https://github.com/pop-os/installer). distinst sets the keyboard settings & locales via `localectl`, and `update-initramfs -u` is run at a later time, which should be carrying these settings into the initramfs, and thus cryptsetup should be using that locale to configure the keyboard. The installer additionally uses `gsettings` and `xsetkbmap` to set the keyboard layout in the installer immediately after selecting a layout.

There was a bug in Ubuntu 17.10 which ignored these values, and which did not affect Debian, but Canonical fixed the bug for 18.04 at release (maybe?). May be an issue with one of Canonical's init scripts which isn't loading the right key map?

**Comment by brs17** [comment] 2018-06-27 15:04
This definitely seems to be a duplicate of https://github.com/pop-os/pop/issues/120 Going to close this. Feel free to add additional information as needed or requested there.

**Closed by brs17** 2018-06-27 15:04 UTC
